name: Backend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: pp4-backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run all unit and mock tests (no DB)
        run: MOCK_TESTS=1 npx vitest run

  build-and-push:
    needs: test  # Deshabilitado temporalmente
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.EC2_PROJECT_PATH || '/home/ubuntu/devops-tpi-infra' }}
            echo "🚀 Iniciando deployment del backend..."

            # Descargar la nueva imagen
            docker-compose pull backend

            # Parar el backend actual para evitar conflictos
            docker-compose stop backend

            # Remover el contenedor anterior
            docker-compose rm -f backend

            # Recrear solo el servicio backend
            docker-compose up -d backend

            # Esperar un momento para que inicie
            sleep 5

            # Limpiar imágenes no utilizadas
            docker image prune -f

            # Verificar que el servicio esté corriendo
            echo "🔍 Verificando estado del backend..."
            docker-compose ps backend

            # Mostrar logs si hay problemas
            echo "📋 Últimos logs del backend:"
            docker-compose logs --tail=20 backend

            echo "✅ Backend desplegado exitosamente!"
